### ISSUE TITLE
[Question]How can I add a cover to an opus file ?

### ISSUE THREAD

**Issue by sebma** [fmang/opustags#50]
Hi,

How can I add a cover to an opus file ?

**Comment by fmang** [comment]
I don’t think it’s something specific to Opus, but more like a convention followed by most of Xiph’s formats. See https://wiki.xiph.org/VorbisComment#METADATA_BLOCK_PICTURE

opustags does not generate that tag, but if you dump the base64 data as a regular comment it should work. Note however that opustags does not currently support tags exceeding 64kB.

I saw your question on Stack Overflow (https://superuser.com/questions/1385109/add-album-art-cover-to-an-ogg-opus-file-from-the-command-line). How about trying hackerb9’s answer to generate a recoded Opus with the right tags using opusenc, then reproducing the tags from the recoded file to the original one using opustags? The command for reproducing tags is `opustags merged.opus | opustags -S audio.opus -o final.opus`. Though that solution is quite wasteful, the result should be just right.

Maybe someday opustags will support cover arts. Someone once hacked opustags for that, see https://github.com/fmang/opustags/pull/21.

**Comment by sebma** [comment]
@fmang Thanks a lot. I'll look into it.

**Comment by iconoclasthero** [comment]
I'm interested in this as a future option.

**Comment by shmerl** [comment]
This fork had a feature for adding a cover, but it was deleted: https://github.com/zvezdochiot/opustags

**Comment by zvezdochiot** [comment]
@shmerl say:
>but it was deleted: https://github.com/zvezdochiot/opustags

https://github.com/Sound-Linux-More/libopustags

**Comment by shmerl** [comment]
Oh, thanks for the pointer!

**Comment by shmerl** [comment]
Would it make sense to merge these projects since opustag is active now too?

**Comment by zvezdochiot** [comment]
@shmerl say:
>Would it make sense to merge these projects since opustag is active now too?

Opustags writes multi-page meta correct. In libopustag, multi-page metas are written with a small error == warning. But I can't stand C++, so there won't be any merging under any pretext.

See also: #58

**Comment by fmang** [comment]
My recent works on 1.7.0 for supporting multi-page headers made support for cover arts one step closer. I’ve just added --set-cover and --output-cover in the master branch if anyone would like to try. I will probably release the feature by the end of the month.

**Comment by mrfragger** [comment]
to add with ffmpeg is really hard....must rely on opustags to get the accurate base64 data

opustags --output-cover cover.png some.opus
then decoding just the top portion shows RDF metadata

������	image/png����������������������HىPNG

���
IHDR��������}V���gAMA��a��� cHRM��z&���������u0��`��:��pQ<���eXIfMM�*������������������J�������R(�������i�������Z�������H������H�������������������������������	pHYs�������iTXtXML:com.adobe.xmp�����<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 6.0.0">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:tiff="http://ns.adobe.com/tiff/1.0/"
            xmlns:exif="http://ns.adobe.com/exif/1.0/">
         <tiff:YResolution>72</tiff:YResolution>
         <tiff:ResolutionUnit>2</tiff:ResolutionUnit>
         <tiff:XResolution>72</tiff:XResolution>
         <tiff:Orientation>1</tiff:Orientation>
         <exif:PixelXDimension>1689</exif:PixelXDimension>
         <exif:ColorSpace>1</exif:ColorSpace>
         <exif:PixelYDimension>720</exif:PixelYDimension>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>

ffmpeg -y -i some.opus -i out.opus.ffmetadata -map_chapters 1 -map 0:a -metadata:s:a METADATA_BLOCK_PICTURE="$(cat ~/.config/mpv/extrastuff/base64.txt)" -c copy meta.opus ; ffprobe meta.opus

  Stream #0:1: Video: png, rgb24(pc, gbr/unknown/unknown), 1280x720, 90k tbr, 90k tbn (attached pic)
      Metadata:
        comment         : Cover (front)
        title           : Front cover

anyway the original png 1280x720  black image is 3KB....if I used freac or kid3 and even opustags to add coverart then I can get the compliant base64 decoded image with necessary RDF metadata evidently.

You can also just paste in the metadata instead of keeping a file

ffmpeg -i "$bname.opus" -i $metafile -map_chapters 1 -map 0:a -metadata:s:a METADATA_BLOCK_PICTURE="AAAAAwAAAAlpbWFnZS9wbmcAAAALRnJvbnQgY292ZXIAAAUAAAAC0AAAABgAAAAAAAAOLYlQTkcNChoKAAAADUlIRFIAAAUAAAAC0AgCAAAAQB9KAQAAAaV6VFh0UmF3IHByb2ZpbGUgdHlwZSBleGlmAAB42qVUWXLDIAz91yl6BLQY8HEcG2Z6gx6/Twp27TSdZlppAPlJaCWh9vHe6c0pl0Q2lZrnnBPIZptlgVDTnVy+YcmQXZXTTpzm2IMIaxrwRbHdryeWK76fvDw4shGdb1fFjkt9cCT3Qz0AZLbhaN4DKeAnkfNcS7Kv72Vc7MPhBItSJZGqNBVfHkV9mS44K/bwDkQhayCq7jD6hKjFUx8ZxVWBmmc+KyJxHR0/4bCHe40mXZt91H5VHEPQK74dXRqUwztTROUT+GQirwyEnk0kyjo12HZJrvhUv/KnmEDfau8tLGyxjIeZx8va58fDDs/TNMpWuHRWyDgJ2xSc0dIVb7oM7njTN+S7MqfOAvbTSTnzygWn8cJTYJWgr/jcwD1YuYiIiXATw4UGrB258AhbInBD4JoabIzgzbj9n+k3g95XbxH7D9mnVGPY4mPxYhnPCnvvtPpIplNrfyYMJKyN03dbegR24xccH7aeE/1uvPk/0eoFjXK8mKQdKa7154z+Si86Kh2ZzfQJg6sf3SiREFwAAAADc0JJVAgICNvhT+AAAAGaaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8P3hwYWNrZXQgYmVnaW49J++7vycgaWQ9J1c1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCc/Pgo8eDp4bXBtZXRhIHhtbG5zOng9J2Fkb2JlOm5zOm1ldGEvJyB4OnhtcHRrPSdJbWFnZTo6RXhpZlRvb2wgMTIuNzYnPgo8cmRmOlJERiB4bWxuczpyZGY9J2h0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMnPgoKIDxyZGY6RGVzY3JpcHRpb24gcmRmOmFib3V0PScnCiAgeG1sbnM6cHJpc209J2h0dHA6Ly9wcmlzbXN0YW5kYXJkLm9yZy9uYW1lc3BhY2VzL2Jhc2ljLzIuMC8nPgogIDxwcmlzbTp3b3JkQ291bnQ+MTQ8L3ByaXNtOndvcmRDb3VudD4KIDwvcmRmOkRlc2NyaXB0aW9uPgo8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo8P3hwYWNrZXQgZW5kPSdyJz8+cCxxFgAACo5JREFUeJztwTEBAAAAwqD1T+1vBqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACANzVGAAHdUIFMAAAAAElFTkSuQmCC" -c copy "$bname-meta.opus" -v quiet
