### ISSUE TITLE
feature request: support globs for -d

### ISSUE THREAD

**Issue by vargobj** [fmang/opustags#67]
usecase:
When **re**indexing an opus file (i.e., an opus file that already has a time/chapter name index), it appears that the only way to remove the index is to iterate through each of those chapter tags (which must be known) and deleted using -d:
```
#!/bin/bash

title=Title\ for\ Testing\ --\ Audiobook.opus
tags=( $(opustags "$title") )
tags2=( $(printf '%s\n' "${tags[@]%=*}"|grep CHAPTER|sort -u) )
printf "%s\n" "${tags2[@]}"
for i in "${tags2[@]}"
  do
    opustags -i -d "$i" "$title"
  done

mediainfo "$title"

exit
```

` $ opustags -d CHAPTER* ` appears to me to be far simpler than the above loop.

**Comment by vargobj** [comment]
The time per tag for removal is also quite high.  A 48-part book took 4:20 m:ss, 4 minutes of that being the chapter tag deletion.

**Comment by zvezdochiot** [comment]
@vargobj , why delete chapters from a book? X(

**Comment by vargobj** [comment]
In order to **re**index a book, the old index must be removed, otherwise all the old CHAPTER### information will be there along with the new information.

```
if [[ "$(opustags "$title")" = *CHAPTER* ]]
  then
    tags=( $(opustags "$title") )
    tags=( $(printf -- '-d%s\n' "${tags[@]%=*}"|\grep CHAPTER|sort -u) )
    opustags "${tags[@]}" -i "$title"
    ck4tags=( "$(opustags "$title" | grep --color=always -i chapter)" ) &&
    printf 'Error!\nCHAPTER tags still present in opus file.\n%s\nexit 1' "${ck4tags[@}}" && exit 1
  else
    printf 'Mediainfo of existing %s:\n' "$title"
    mediainfo "$title"
fi
```

Obviously, if would be easier if I could just
 `opustags -i -dCHAPTER* $title 2>/dev/null || exit 1`

**Comment by zvezdochiot** [comment]
@vargobj 
```shell
opustags -D
```
;)

**Comment by fmang** [comment]
Sounds like a good proposal. By replacing the strncasecmp with fnmatch we could get a working solution. We must ensure however that * is not a valid character in tag names or, if it is, that there exists a way to escape the * to match it literally. Alternatively, we could add an optional value to --delete-all and write `-D=CHAPTER*`. That latter option might be less surprising because it is plural.

As zvezdochiot suggested, you can use --set-all to replace all the tags at once. In your case, assuming they all fit in one line :

```bash
opustags file.opus | grep -v ^CHAPTER | opustags -i file.opus -S
```

When a tag value spans multiple lines, you would need to filter out the continuation lines starting with TAB (`\t`) too. Some awk would do the trick.

**Comment by fmang** [comment]
After more consideration, I have decided to introduce a -z flag to delimit tags by the NUL character instead of line feeds. This took inspiration from GNU tools like grep or sed that use -z too for the same purpose and the same goal: supporting embedded newlines. By leveraging the power of grep and sed, many more use cases will be supported.

To support multi-line tags, the previous command can now be written as:

```bash
opustags -z file.opus | grep -z -v ^CHAPTER | opustags -z -i file.opus -S
```

This new option is ready in the master branch, and I plan to release it this week unless you have any remarks. I have documented this use case in the man page.

**Comment by iconoclasthero** [comment]
I'll explore the new feature and update my script as appropriate, thank you for looking into it.

**Comment by vargobj** [comment]
> Sounds like a good proposal. By replacing the strncasecmp with fnmatch we could get a working solution. We must ensure however that * is not a valid character in tag names or, if it is, that there exists a way to escape the * to match it literally. Alternatively, we could add an optional value to --delete-all and write `-D=CHAPTER*`. That latter option might be less surprising because it is plural.
> 
> As zvezdochiot suggested, you can use --set-all to replace all the tags at once. In your case, assuming they all fit in one line :
> 
> ```shell
> opustags file.opus | grep -v ^CHAPTER | opustags -i file.opus -S
> ```
> 
> When a tag value spans multiple lines, you would need to filter out the continuation lines starting with TAB (`\t`) too. Some awk would do the trick.

I did not go to the trouble of individually removing the CHAPTER tags, i.e., while still preserving all of the remaining metadata, just, instead, to delete everything and start from scratch. No, I didn't miss those flags.

So what's the deal here, can I use globs now or not?

**Comment by fmang** [comment]
The idea of the change is you can relay complex edition to an external program. In your case, you can use grep to delete tags matching a pattern. Note that in my command line, the file.opus is the same on both ends, and that’s a key point.

The first opustags reads the tags from the file, so you’d get something like:

```
ARTIST=Someone
TITLE=Something
CHAPTER1=…
CHAPTER2=…
```

Then, grep -v removes the tags starting with CHAPTER, so you get:

```
ARTIST=Someone
TITLE=Something
```

Finally, the last opustags -S writes the filtered tags back to the original file.

Feel free to experiment with my last command (with all the -z) on a copy of the files you’d like to process and see the result.
