### ISSUE TITLE
Feature request: equivalent of metaflac's remove-all-tags-except

### ISSUE THREAD

**Issue by anonymous5555522222** [fmang/opustags#68]
`--remove-all-tags-except=NAME1[=NAME2[=...]] Remove all tags, except the vendor
                      string and the tag names specified. Tag names must be
                      separated by an = character.`

Example:
`--remove-all-tags-except=TITLE=ARTIST=METADATA_BLOCK_PICTURE`
This would delete every tag except the title and artist tags, and the cover art, from an Opus file.

Thank you for this tool, it works perfectly.

**Comment by fmang** [comment]
This is quite a specific feature request. opustags provides --edit to leverage the power of your text editor, or --set-all to allow scripting. For example, to get the behavior you need, you can do:

```
opustags file.opus | grep -E '^(TITLE|ARTIST|METADATA_BLOCK_PICTURE)=' | opustags -S -i file.opus
```

The caveat is that it truncates multi-line tags, but the three tags you listed are all supposed to fit on one line.

As a more generic approach, I would consider something like --keep=TAG that, when combined with --delete-all or --set-all, prevents the selected tags from being deleted. Or, to reuse the existing options, allow specifying --add=TAG without a value, so that `--delete-all --add TITLE` would mean “delete all the tags then add TITLE with the value it had before”.

**Comment by anonymous5555522222** [comment]
> As a more generic approach, I would consider something like --keep=TAG that, when combined with --delete-all or --set-all, prevents the selected tags from being deleted.

This one sounds good to me as long as various tags can be requested (`--keep TITLE --keep ARTIST` or `--keep TITLE=ARTIST`), the other one makes me think that it would result in adding `TITLE=` to a file.

**Comment by fmang** [comment]
I have ended up adding a -z flag. See <https://github.com/fmang/opustags/issues/67#issuecomment-2084627133>.

The following command should solve your use case and also support multi-line tags, assuming you use GNU grep:

```bash
opustags -z file.opus | grep -z -E '^(TITLE|ARTIST|METADATA_BLOCK_PICTURE)=' | opustags -z -S -i file.opus
```

**Comment by anonymous5555522222** [comment]
> I have ended up adding a -z flag. See [#67 (comment)](https://github.com/fmang/opustags/issues/67#issuecomment-2084627133).
> 
> The following command should solve your use case and also support multi-line tags, assuming you use GNU grep:
> 
> ```shell
> opustags -z file.opus | grep -z -E '^(TITLE|ARTIST|METADATA_BLOCK_PICTURE)=' | opustags -z -S -i file.opus
> ```

I have tested this one-liner command with commit `0067162`, and it works great. Thanks!

**Comment by fmang** [comment]
Great! Thank you for your feedback. I’m closing the issue.
